version: '3.7' 
services: 
 ookla: 
   image: djkormo/ooklaspeedtest:main 
   container_name: ooklaspeedtest 
   deploy:
    resources:
      limits:
        cpus: 0.50
        memory: 512M
# WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
#      reservations:
#       cpus: 0.25
#      memory: 128M

   networks: 
     - ooklaspeedtest
   
   restart: always 
   ports: 
     - 8080:8080 
     - 5060:5060 
     
 fireprobe: 
   image: djkormo/fireprobe:main 
   container_name: fireprobe 
   deploy:
    resources:
      limits:
        cpus: 0.50
        memory: 512M
   networks: 
     - fireprobe
   restart: always 
   ports: 
     - 9113:9113 
     - 9114:9114 
     
 rfbenchmark: 
   image: djkormo/rfbenchmark:main 
   container_name: rfb-testserver 
   deploy:
    resources:
      limits:
        cpus: 0.50
        memory: 512M
   networks: 
     - rfbenchmark
 
   restart: always 
   ports: 
     - 8888:8888 
   environment: 
     - RFB_LOG_LEVEL=debug 

networks:
  ooklaspeedtest:
  fireprobe:
  rfbenchmark:
